spring:
  application:
    name: imgt
  datasource:
    url: jdbc:postgresql://localhost:8000/imgt_db
    username: imgt_user
    password: imgt_password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 60000
  session:
    store-type: redis
    timeout: 30m
  cloud:
    aws:
      region:
        static: us-east-2
    credentials:
      acess-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    sqs:
      enabled: true
      # Configurações específicas para FIFO
      listener:
        max-concurrent-messages: 1  # FIFO processa em ordem, geralmente 1 por vez
        max-messages-per-poll: 10

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.security: DEBUG
    com.imgt: DEBUG

# Server Configuration
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always